name: Nick
version: ${project.version}
main: moe.orangemc.nick.NickPlugin
api-version: 1.16
authors: [ Lucky_fish0w0 ]

depend:
  - ProtocolLib
softdepend:
  - ViaBackwards

commands:
  nick:
    description: change your nickname
    permission: nick.command

permissions:
  nick.command:
    default: op
